### PR TITLE
Add class-based typed api view

### PR DESCRIPTION
**Pull request by sjquant**
I use `APIView` in my Django project a lot, so I created `TypedAPIView` class.
I think this class will broaden the adoption of your library.

I overrided drf's `dispatch` method in `APIView` class. I only modified following part of original `dispatch` method.

```py
typed_params = [
    p
    for n, p in inspect.signature(handler).parameters.items()
    if n != "self"
]
transformed = transform_view_params(typed_params, request, kwargs)

response = handler(*transformed)
```

I use this class in my project, and it is working well. But, I couldn't create appropriate test codes.
Could you(@rsinger86 ) create them? Or, you can give me some guidance for test codes.

### CODE REVIEW

**Comment by rsinger86** [comment]
Thanks, this looks like a nice addition. I've been swamped with other things, but I hope to go deeper on this soon.

**Comment by sjquant** [comment]
@rsinger86 Thanks for reply and your time : )

**Comment by rsinger86** [comment]
Looking good! You could add a test module file `test_typed_api_view_class.py` here:
https://github.com/rsinger86/drf-typed-views/tree/master/test_project/testapp/tests

You can add views, models, URL config to the testapp to add a new path through the application that uses this new class:
https://github.com/rsinger86/drf-typed-views/tree/master/test_project/testapp
https://github.com/rsinger86/drf-typed-views/blob/master/test_project/urls.py

The test module can reverse the URLs to exercise the new class end-to-end.

**Comment by sjquant** [comment]
@rsinger86 Sorry for late response. I had busy months. I added some tests to class-based typed api view. Please, take a look and let me know if there's an issue. Thank you 😄

**Comment by sjquant** [comment]
@rsinger86 Could you review my code?

**Pull request closed without merging**
